### ISSUE TITLE
Logos needed, you deleted them.

### ISSUE THREAD

**Issue by epicprogramming101** [switchpiggy/OnlineForum#4]
<img width="392" alt="Screen Shot 2019-11-11 at 9 40 21 PM" src="https://user-images.githubusercontent.com/46630586/68645246-4ffc5d80-04cc-11ea-9ec0-04ae5b46a5e9.png">
use the same image as favicons

**Comment by epicprogramming101** [comment]
#markdown?

**Comment by epicprogramming101** [comment]
*markdown*

**Comment by epicprogramming101** [comment]
**markdown**

**Comment by epicprogramming101** [comment]
Just testing out markdown

**Comment by switchpiggy** [comment]
ok solved

**Comment by epicprogramming101** [comment]
No. Not solved, you didn't add logo to the public folder
